development:
  adapter: postgresql
  encoding: unicode
  database: watermark-dev
  pool: 5
  username: falon
  password: 3141-5926-5359

test:
  adapter: postgresql
  encoding: unicode
  database: watermark-test
  pool: 5
  username: falon
  password: 3141-5926-5359
